### ISSUE TITLE
curies.rs

### ISSUE THREAD

**Issue by ktk** [IoannisNezis/sparql-language-server#5]
Purely FYI, feel free to close immediately:

https://biopragmatics.github.io/curies.rs/

Might be useful.

And also related, we keep a curated list of common prefixes here for our own tooling: https://github.com/zazuko/rdf-vocabularies

**Comment by IoannisNezis** [comment]
Nice , thank you.

Will be useful for the "shrinking iris" code action!

Btw,
i can't wait continuing this project.
I need to complete a report and some other stuff and will continue then.

Next step is to build a more powerful, error resilient, parser to handle incomplete queries.
